import ScheduleCalendar from './ScheduleCalendar'

const tones = ['purple', 'blue', 'orange']

function formatDate(value) {
  if (!value) return 'Unscheduled'
  const date = new Date(`${value}T00:00:00`)
  return Number.isNaN(date.valueOf()) ? value : new Intl.DateTimeFormat('en', { month: 'short', day: 'numeric' }).format(date)
}

function className(item) {
  return item.subjectName ? item.subjectName + ' · ' + item.subject : item.subject
}

export function PlannerCalendar({ goTo, classes, clubs, events, tasks, studyPlan }) {
  const upcoming = [
    ...events.map((item) => ({ id: `event-${item.id}`, title: item.name, date: item.date, detail: `${item.startTime}–${item.endTime}`, tone: 'orange', type: 'Event' })),
    ...tasks.filter((item) => !item.isRecurring && item.date).map((item) => ({ id: `task-${item.id}`, title: item.title, date: item.date, detail: item.startTime && item.endTime ? `${item.startTime}–${item.endTime}` : 'Task', tone: 'purple', type: 'Task' })),
    ...classes.flatMap((course) => course.assessments.map((item) => ({ id: `assessment-${item.id}`, title: `${className(course)} assessment`, date: item.date, detail: `Topics ${item.topicStart}–${item.topicEnd} · ${item.weight}%`, tone: 'blue', type: 'Assessment' }))),
  ].sort((a, b) => a.date.localeCompare(b.date))
  return <div className="page-view"><section className="page-intro"><div><p className="eyebrow">Your saved schedule</p><h1>Make space for everything.</h1><p>Weekly classes, club meetings, events, tasks, and your daily study block in one live calendar.</p></div><button className="create-button" onClick={() => goTo('manage', 'events')}>+ Add event</button></section><section className="calendar-page-card"><div className="calendar-page-toolbar"><strong>Your weekly schedule</strong><span className="calendar-legend">Tasks, classes, clubs, events, and study</span></div><ScheduleCalendar classes={classes} clubs={clubs} events={events} tasks={tasks} studyPlan={studyPlan} /></section><section className="page-section"><div className="section-heading"><div><p className="eyebrow">Deadlines and plans</p><h2>What’s coming up</h2></div><button className="subtle-action" onClick={() => goTo('manage', 'tasks')}>Manage tasks</button></div><div className="agenda-list">{upcoming.length ? upcoming.map((item) => <article key={item.id}><span>{formatDate(item.date)}</span><div><h3>{item.title}</h3><p>{item.detail}</p></div><span className={`agenda-type ${item.tone}`}>{item.type}</span></article>) : <p className="empty-state">No dated tasks, events, or assessments yet.</p>}</div></section></div>
}

export function PlannerCourses({ goTo, classes }) {
  const assessments = classes.flatMap((course) => course.assessments.map((assessment) => ({ ...assessment, subject: className(course) }))).sort((a, b) => a.date.localeCompare(b.date))
  return <div className="page-view"><section className="page-intro"><div><p className="eyebrow">Your current semester</p><h1>Your classes, in balance.</h1><p>See each class, its assessments, and covered topics at a glance.</p></div><button className="create-button" onClick={() => goTo('manage', 'classes')}>+ Add class</button></section><section className="course-grid">{classes.length ? classes.map((course, index) => <article className={`course-card ${tones[index % tones.length]}`} key={course.id}><div className="course-card-head"><span className={`course-pill ${tones[index % tones.length]}`}>CLASS</span></div><h2>{className(course)}</h2><p>{course.day} · {course.startTime}–{course.endTime}</p><div className="course-progress"><span><b>{course.assessments.length}</b> assessment{course.assessments.length === 1 ? '' : 's'}</span></div></article>) : <p className="empty-state">No classes yet. Add one in Edit plan.</p>}</section><section className="page-section"><div className="section-heading"><div><p className="eyebrow">All coursework</p><h2>Assessments</h2></div></div><div className="assignment-table">{assessments.length ? <><div className="assignment-row table-head"><span>Class</span><span>Topics</span><span>Due</span><span>Weight</span></div>{assessments.map((item) => <div className="assignment-row" key={item.id}><strong>{item.subject}</strong><span>Topics {item.topicStart}–{item.topicEnd}</span><span>{formatDate(item.date)}</span><span className="status-tag upcoming">{item.weight}%</span></div>)}</> : <p className="empty-state">No assessments yet.</p>}</div></section></div>
}

export function ClassTopics({ classes }) {
  return <section className="course-topics-section"><div className="section-heading"><div><p className="eyebrow">Class content</p><h2>Topics by class</h2></div><span className="topics-note">Edit topic ranges in Edit plan</span></div><div className="topics-grid">{classes.length ? classes.map((course, index) => { const highestTopic = Math.max(0, ...course.assessments.map((assessment) => Number(assessment.topicEnd) || 0)); const topics = course.topics.length ? course.topics : Array.from({ length: highestTopic }, (_, topicIndex) => ({ number: topicIndex + 1, title: `Topic ${topicIndex + 1}` })); return <article className={`topic-course ${tones[index % tones.length]}`} key={course.id}><div className="topic-course-title"><span className="course-pill">CLASS</span><h3>{className(course)}</h3></div>{topics.length ? <ol>{topics.map((topic) => <li key={topic.number}><span>{topic.number}</span><p>{topic.title}</p></li>)}</ol> : <p className="empty-topics">No topic titles yet.</p>}</article> }) : <p className="empty-state">Add a class to start listing topics.</p>}</div></section>
}

export function PlannerClubs({ goTo, clubs, events }) {
  return <div className="page-view"><section className="page-intro"><div><p className="eyebrow">Life outside your classes</p><h1>Keep the good stuff in view.</h1><p>Weekly meetings and standalone events are protected inside your plan.</p></div><button className="create-button" onClick={() => goTo('manage', 'clubs')}>+ Add club</button></section><section className="club-grid">{clubs.length ? clubs.map((club, index) => { const linkedEvents = events.filter((event) => event.clubId === club.id); const tone = index % 2 ? 'photo' : 'debate'; return <article className={`club-card ${tone}`} key={club.id}><div className="club-card-top"><span className="club-icon">C</span></div><p className="eyebrow">{club.hasWeeklyMeeting ? 'Weekly commitment' : 'Flexible club'}</p><h2>{club.name}</h2><p>{club.hasWeeklyMeeting ? `Every ${club.day} · ${club.startTime}–${club.endTime}` : 'No weekly meeting scheduled'}</p><div className="club-footer"><span>{linkedEvents.length} event{linkedEvents.length === 1 ? '' : 's'} this term</span><button onClick={() => goTo('manage', 'clubs')}>Edit club →</button></div></article> }) : <p className="empty-state">No clubs yet. Add one in Edit plan.</p>}</section><section className="page-section"><div className="section-heading"><div><p className="eyebrow">Dates to save</p><h2>Club events</h2></div><button className="subtle-action" onClick={() => goTo('manage', 'events')}>Edit events</button></div><div className="club-events">{events.length ? events.map((event) => { const club = clubs.find((item) => item.id === event.clubId); return <article key={event.id}><span className="event-date"><b>{event.date.slice(-2)}</b>{event.date.slice(5, 7)}</span><div><span className="course-pill green">{club?.name ?? 'STANDALONE'}</span><h3>{event.name}</h3><p>{event.endDate ? `${formatDate(event.date)} to ${formatDate(event.endDate)}` : formatDate(event.date)} · {event.startTime}–{event.endTime}</p></div></article> }) : <p className="empty-state">No events yet.</p>}</div></section></div>
}
